[package]
name = "ascii-art"
version = "0.1.0"
authors = ["Sylvia Waldron"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
structopt = "0.3"
colored = "2"
itertools = "0.10"
